name: "Запрос на функцию"
description: "Предложить идею или улучшение"
title: "[Идея] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Какую задачу это решает
      description: Что сейчас неудобно или невозможно сделать
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Как вы это видите
    validations:
      required: true
